image: node:16.15.0-slim

stages:
  - testing
  - build
  - deploy

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  SERVER_HOST: 18.213.102.175
  SERVER_USER: ubuntu
  PROJECT_ROOT: ~/tecky_c20tw_bad_project
  WEB_SERVER_ROOT: Express
  WEB_SERVER_NAME: Braille

testing:
  services:
    - postgres:14.3-alpine

  artifacts:
    paths:
      - $WEB_SERVER_ROOT/node_modules

  before_script:
    - cd Express
    - npm i -g pnpm
    - pnpm i

  stage: testing
  script:
    - npm test

build:
  stage: build
  dependencies:
    - testing

  artifacts:
    paths:
      - $WEB_SERVER_ROOT/dist

  before_script:
    - cd $WEB_SERVER_ROOT
    - npm install

  script:
    - npm run build

deploy:
  stage: deploy
  image: ubuntu:22.04

  dependencies:
    - testing

  before_script:
    - apt update
    - apt install --yes rsync openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
    - echo "Host server" >> ~/.ssh/config
    - echo "  Hostname $SERVER_HOST" >> ~/.ssh/config
    - echo "  User $SERVER_USER" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/id_rsa " >> ~/.ssh/config
    - cd $WEB_SERVER_ROOT

  script:
    - rsync -SavLP dist "server:$PROJECT_ROOT/$WEB_SERVER_ROOT"
    - ssh server "
      source ~/.nvm/nvm.sh &&
      cd $PROJECT_ROOT/$WEB_SERVER_ROOT &&
      git fetch &&
      git checkout $CI_COMMIT_SHA &&
      pnpm i --prod &&
      cd dist &&
      npx knex migrate:latest &&
      pm2 start --name $WEB_SERVER_NAME server.js ||
      pm2 reload $WEB_SERVER_NAME
      "
