
image: node:16.15.0-slim

stages:
  - test
  - deploy

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

  test:
    services:
      - postgres:14.3 -alpine
    before_script:
      - cd Tecky_C20TW_BAD_Project/Express
      - npm i -g pnpm
      - pnpm i
    stage: test
    script:
      - npm test

build:
  stage: build
  dependencies:
    - test
  before_script:
    - cd Tecky_C20TW_BAD_Project/Express
  script:
    - npm run build
