image: node:16.15.0-slim

stages:
  - testing
  - deploy
  

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: CICD
  POSTGRES_PASSWORD: CICD
  POSTGRES_HOST: postgres

  testing:
    services:
      - postgres:14.3 -alpine
    before_script:
      - cd Tecky_C20TW_BAD_Project/Express
      - npm i -g pnpm
      - pnpm i
    stage: testing
    script:
      - npm test


   build:
    dependenies:
      - test
     before_script:
       - cd Tecky_C20TW_BAD_Project/express  
    stage: build
    script:
      - npm run build

  deploy:
    dependenies:
       - build
    before_script:
    - apt update
    - apt install --yes git openssh-client
    - cd Tecky_C20TW_BAD_Project
    stage: deploy
    only:
     - production
    image:
    - ububtu:22.04
    script:
      - echo "commit_hash = $CI-cOMMIT_SHA"
      - ssh server "
        source -/.nvm/nvm.sh &&\
        cd ~/Tecky_C20TW_BAD_Project &&\
        git fetch &&\
        pnpm i -- prod &&\
        cd Tecky_C20TW_BAD_Project/express &&\
        yarn knex migrate:latest &&\
        forever restart server.ts;" 
