image: node:16.15.0-slim

stages:
  - testing

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

testing:
  services:
    - postgres:latest

  before_script:
    - npm i -g pnpm
    - pnpm i

  stage: testing
  script:
    - npm test
