stages:
  - docker
services:
  - docker:dind
docker-job:
 stage: docker
 image: docker:dind
 scripts:
  - docker build .









# image: node:latest

# stages:
#   - testing
#   - build
#   - deploy
  

# variables:
#   POSTGRES_DB: braille
#   POSTGRES_USER: CICD
#   POSTGRES_PASSWORD: CICD
#   POSTGRES_HOST: postgres

#   testing:
#     services:
#       - postgres:latest
#     before_script:
#       - cd Tecky_C20TW_BAD_Project/express
#       - yarn install
#       - yarn knex migrate:latest --env test
#     stage: testing
#     script:
#       - yarn jest


#    build:
#     dependenies:
#       - test
#      before_script:
#        - cd Tecky_C20TW_BAD_Project/express  
#     stage: build
#     script:
#       - yarn init
#       - yarn run build

#   deploy:
#   dependenies:
#       - build
#     before_script:
#       - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
#       - eval $(ssh-agent -s)
#       - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private.pem
#       - chmod 400 private.pem
#       - ssh-add private.pem > /dev/null
#       - mkdir -p ~/.ssh
#       - chmod 700 ~/.ssh
#       - ssh-keyscan -H  vxxxxc > ~/.ssh/known_hosts
#       - chmod 644 ~/.ssh/known_hosts
#     stage: deploy
#     script:
#       - ssh ubuntu@vxxxxc
#         "cd Tecky_C20TW_BAD_Project;
#         git pull origin main;
#         yarn install;
#         yarn knex migrate:latest;"
