image: node:16.15.0-slim

stages:
  - testing
  - deploy
  

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: CICD
  POSTGRES_PASSWORD: CICD
  POSTGRES_HOST: postgres

  testing:
    services:
      - postgres:14.3 -alpine
    before_script:
      - cd Tecky_C20TW_BAD_Project/Express
      - npm i -g pnpm
      - pnpm i
    stage: testing
    script:
      - npm test

