image: node:latest

stages:
  - testing

variables:
  POSTGRES_DB: bad009-test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

testing:
  services:
    - postgres:latest

  before_script:
    - yarn install
  stage: testing
  script:
    - echo "hi~"