image: node:16.15.0-slim

stages:
  # - testing
  # - build
  - deploy

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  SERVER_HOST: 18.213.102.175
  SERVER_NAME: vxxxxc
  PROJECT_ROOT: ~/tecky_c20tw_bad_project

testing:
  services:
    - postgres:latest

  before_script:
    - cd Express
    - npm i -g pnpm
    - pnpm i

  stage: testing
  script:
    - npm test

build:
  # dependencies:
  #   - testing
  before_script:
    - cd Express
    - yarn add typescript
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  image: ubuntu:22.04

  dependencies:
    - testing
  before_script:
    - apt update
    - apt install --yes git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -keyscan -H  vxxxxc > ~/.ssh/known_hosts
    - cd Tecky_C20TW_BAD_Project

  script:
    - echo "Hi~"
