image: node:16.15.0-slim

stages:
  # - testing
  - build
  - deploy

variables:
  POSTGRES_DB: braille
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

# testing:
#   services:
#     - postgres:latest

#   before_script:
#     - cd Tecky_C20TW_BAD_Project/Express
#     - npm i -g pnpm
#     - pnpm i

#   stage: testing
#   script:
#     - echo "hi~"

build:
  # dependencies:
  #   - testing
  before_script:
    - cd Tecky_C20TW_BAD_Project/express
  stage: build
  script:
    - npm run build

deploy:
  dependencies:
    - build
  before_script:
    - apt update
    - apt install --yes git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -keyscan
    - cd Tecky_C20TW_BAD_Project

  stage: deploy

  only:
    - production

  script:
    - echo "Hi~"
